//#############################################################################
// Links & Learning resources
//#############################################################################

// three official supercollider websites
("open 'http://supercollider.github.io'").unixCmd // the newest one
("open 'http://supercollider.sourceforge.net'").unixCmd // the most useful one
("open 'http://audiosynth.com'").unixCmd // the original. no-nonsense 90s

// large repository/community for SC code
("open 'http://sccode.org'").unixCmd

// SC mailing list archive. Mailing list is THE resource if you want community support
("open 'http://bit.ly/1zhaBVa'").unixCmd

// Tutorials
//----------
("open 'http://bit.ly/1zXVcjw'").unixCmd // Eli Fieldsteel youtube channel
("open 'http://www.mat.ucsb.edu/275/CottleSC3.pdf'").unixCmd // David Michael Cottle's book
("open 'http://modularbrains.net/dx490a/'").unixCmd// Stelios Manousakis' series
// http://sc3howto.blogspot.com << Charles Celeste Hutchins' tutorial


// Inspiration Copy-Paste
//-----------------------
// - steal this sound book
("open 'http://amzn.to/18WiJFt'").unixCmd // printed book
("open 'http://bit.ly/1FgJNdf'").unixCmd // SC-implemented examples

// live coding examples
("open 'http://www.toplap.org'").unixCmd // live-coding collective
("open 'https://vimeo.com/50069228'").unixCmd // live-coded recreation of Radiohead track

// running on embedded platforms
("open 'http://bit.ly/1ENgxgI'").unixCmd // beagleBone black looper
("open 'http://bit.ly/1xEpLTV'").unixCmd // raspberry pi code repository
